package main

import (
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	if len(file.Messages) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_fast_equal.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	generateHeader(g, file)

	for _, msg := range file.Messages {
		if len(msg.Oneofs) != 0 {
			continue
		}
		generateIsEqualMethod(g, msg)
	}
}

func generateHeader(g *protogen.GeneratedFile, file *protogen.File) {
	g.P("// Code generated by protoc-gen-fast-equal. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
}

func generateIsEqualMethod(g *protogen.GeneratedFile, msg *protogen.Message) {
	if len(msg.Fields) == 0 {
		return
	}
	g.P("// IsEqual is a method for fast comparison")
	g.P("func (m *", msg.GoIdent, ") IsEqual(msg *", msg.GoIdent, ") bool {")

fieldloop:
	for _, fld := range msg.Fields {
		if fld.Desc.IsList() {
			if isComparable(fld) {
				g.P("    if len(m.", fld.GoName, ") != len(msg.", fld.GoName, ") || !slices.Equal(m.", fld.GoName, " msg.", fld.GoName, ") {")
				g.P("        return false")
				g.P("    }")
			} else if fld.Desc.Kind() == protoreflect.MessageKind {
				g.P("    if len(m.", fld.GoName, ") != len(msg.", fld.GoName, ") {")
				g.P("        return false")
				g.P("    }")
				g.P("    for i := 0; i < len(m.", fld.GoName, "); i++ {")
				g.P("        if !m.", fld.GoName, "[i].IsEqual(msg.", fld.GoName, "[i]) {")
				g.P("            return false")
				g.P("        }")
				g.P("    }")
			}
		} else if isComparable(fld) {
			g.P("    if m.", fld.GoName, " != msg.", fld.GoName, "{")
			g.P("        return false")
			g.P("    }")
		} else if fld.Desc.Kind() == protoreflect.MessageKind {
			for _, nestedField := range fld.Message.Fields {
				if !isComparable(nestedField) {
					continue fieldloop
				}
			}
			g.P("    if m.", fld.GoName, " != msg.", fld.GoName, "{")
			g.P("        return false")
			g.P("    }")
		}
	}

	g.P("   return true")
	g.P("}")
	g.P()

	for _, nestedMsg := range msg.Messages {
		generateIsEqualMethod(g, nestedMsg)
	}
}

func isComparable(field *protogen.Field) bool {
	switch field.Desc.Kind() {
	case protoreflect.BoolKind, protoreflect.Int64Kind, protoreflect.Int32Kind,
		protoreflect.Uint64Kind, protoreflect.Uint32Kind, protoreflect.FloatKind,
		protoreflect.EnumKind, protoreflect.StringKind:
		return true
	}
	return false
}
