// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/notes/v1/errors.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        string                 `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_api_notes_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetails) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_api_notes_v1_errors_proto protoreflect.FileDescriptor

const file_api_notes_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x19api/notes/v1/errors.proto\x12\fapi.notes.v1\"&\n" +
	"\fErrorDetails\x12\x16\n" +
	"\x06detail\x18\x01 \x01(\tR\x06detailB.Z,github.com/shft1/grpc-notes/pkg/api/notes/v1b\x06proto3"

var (
	file_api_notes_v1_errors_proto_rawDescOnce sync.Once
	file_api_notes_v1_errors_proto_rawDescData []byte
)

func file_api_notes_v1_errors_proto_rawDescGZIP() []byte {
	file_api_notes_v1_errors_proto_rawDescOnce.Do(func() {
		file_api_notes_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_notes_v1_errors_proto_rawDesc), len(file_api_notes_v1_errors_proto_rawDesc)))
	})
	return file_api_notes_v1_errors_proto_rawDescData
}

var file_api_notes_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_notes_v1_errors_proto_goTypes = []any{
	(*ErrorDetails)(nil), // 0: api.notes.v1.ErrorDetails
}
var file_api_notes_v1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_notes_v1_errors_proto_init() }
func file_api_notes_v1_errors_proto_init() {
	if File_api_notes_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notes_v1_errors_proto_rawDesc), len(file_api_notes_v1_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_notes_v1_errors_proto_goTypes,
		DependencyIndexes: file_api_notes_v1_errors_proto_depIdxs,
		MessageInfos:      file_api_notes_v1_errors_proto_msgTypes,
	}.Build()
	File_api_notes_v1_errors_proto = out.File
	file_api_notes_v1_errors_proto_goTypes = nil
	file_api_notes_v1_errors_proto_depIdxs = nil
}
