// Code generated by protoc-gen-fast-equal. DO NOT EDIT.
// source: api/notes/v1/errors.proto

package v1

// IsEqual is a method for fast comparison
func (m *ErrorDetails) IsEqual(msg *ErrorDetails) bool {
	if m.Detail != msg.Detail {
		return false
	}
	return true
}
