// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/notes/v1/messages.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NoteIDRequest - сообщение ID заметки
type NoteIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteIDRequest) Reset() {
	*x = NoteIDRequest{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteIDRequest) ProtoMessage() {}

func (x *NoteIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteIDRequest.ProtoReflect.Descriptor instead.
func (*NoteIDRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *NoteIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// NoteCreateRequest - сообщение заметки для создания
type NoteCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteCreateRequest) Reset() {
	*x = NoteCreateRequest{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteCreateRequest) ProtoMessage() {}

func (x *NoteCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteCreateRequest.ProtoReflect.Descriptor instead.
func (*NoteCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *NoteCreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteCreateRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

// Note - сообщение заметки
type Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	IsDel         bool                   `protobuf:"varint,4,opt,name=is_del,json=isDel,proto3" json:"is_del,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Note) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Note) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Note) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Note) GetIsDel() bool {
	if x != nil {
		return x.IsDel
	}
	return false
}

func (x *Note) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Note) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// NoteList - сообщение списка заметок
type NoteList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notes         []*Note                `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteList) Reset() {
	*x = NoteList{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteList) ProtoMessage() {}

func (x *NoteList) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteList.ProtoReflect.Descriptor instead.
func (*NoteList) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *NoteList) GetNotes() []*Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

// NoteEvent - событие заметки
type NoteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteEvent) Reset() {
	*x = NoteEvent{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteEvent) ProtoMessage() {}

func (x *NoteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteEvent.ProtoReflect.Descriptor instead.
func (*NoteEvent) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *NoteEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NoteEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// EventResponse - сообщение server-stream
type EventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*EventResponse_Note
	//	*EventResponse_Health
	Event         isEventResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *EventResponse) GetEvent() isEventResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventResponse) GetNote() *NoteEvent {
	if x != nil {
		if x, ok := x.Event.(*EventResponse_Note); ok {
			return x.Note
		}
	}
	return nil
}

func (x *EventResponse) GetHealth() *Health {
	if x != nil {
		if x, ok := x.Event.(*EventResponse_Health); ok {
			return x.Health
		}
	}
	return nil
}

type isEventResponse_Event interface {
	isEventResponse_Event()
}

type EventResponse_Note struct {
	Note *NoteEvent `protobuf:"bytes,1,opt,name=note,proto3,oneof"`
}

type EventResponse_Health struct {
	Health *Health `protobuf:"bytes,2,opt,name=health,proto3,oneof"`
}

func (*EventResponse_Note) isEventResponse_Event() {}

func (*EventResponse_Health) isEventResponse_Event() {}

// Health - сообщение об установлении server-stream
type Health struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Health) Reset() {
	*x = Health{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Health) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Health) ProtoMessage() {}

func (x *Health) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Health.ProtoReflect.Descriptor instead.
func (*Health) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *Health) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Empty - сообщение на установление server-stream
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{7}
}

// MetricRequest - сообщение client-stream
type MetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricRequest) Reset() {
	*x = MetricRequest{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRequest) ProtoMessage() {}

func (x *MetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRequest.ProtoReflect.Descriptor instead.
func (*MetricRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *MetricRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

// SummaryResponse - сообщение по завершении client-stream
type SummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       int64                  `protobuf:"varint,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryResponse) Reset() {
	*x = SummaryResponse{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryResponse) ProtoMessage() {}

func (x *SummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryResponse.ProtoReflect.Descriptor instead.
func (*SummaryResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *SummaryResponse) GetSummary() int64 {
	if x != nil {
		return x.Summary
	}
	return 0
}

var File_api_notes_v1_messages_proto protoreflect.FileDescriptor

const file_api_notes_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/notes/v1/messages.proto\x12\fapi.notes.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\")\n" +
	"\rNoteIDRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"W\n" +
	"\x11NoteCreateRequest\x12\"\n" +
	"\x05title\x18\x01 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x05\x18\x19R\x05title\x12\x1e\n" +
	"\x04desc\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\n" +
	"\x18\xff\x01R\x04desc\"\xf0\x02\n" +
	"\x04Note\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\"\n" +
	"\x05title\x18\x02 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x05\x18\x19R\x05title\x12\x1e\n" +
	"\x04desc\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\n" +
	"\x18\xff\x01R\x04desc\x12\x15\n" +
	"\x06is_del\x18\x04 \x01(\bR\x05isDel\x12A\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tcreatedAt\x12A\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tupdatedAt:m\xbaHj\x1ah\n" +
	"\n" +
	"time.logic\x126the creation time must be earlier than the update time\x1a\"this.created_at <= this.updated_at\"<\n" +
	"\bNoteList\x120\n" +
	"\x05notes\x18\x01 \x03(\v2\x12.api.notes.v1.NoteB\x06\xbaH\x03\xc8\x01\x01R\x05notes\"I\n" +
	"\tNoteEvent\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\"\n" +
	"\x05title\x18\x02 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x05\x18\x19R\x05title\"w\n" +
	"\rEventResponse\x12-\n" +
	"\x04note\x18\x01 \x01(\v2\x17.api.notes.v1.NoteEventH\x00R\x04note\x12.\n" +
	"\x06health\x18\x02 \x01(\v2\x14.api.notes.v1.HealthH\x00R\x06healthB\a\n" +
	"\x05event\"\"\n" +
	"\x06Health\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\a\n" +
	"\x05Empty\"'\n" +
	"\rMetricRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\"+\n" +
	"\x0fSummaryResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\x03R\asummaryB.Z,github.com/shft1/grpc-notes/pkg/api/notes/v1b\x06proto3"

var (
	file_api_notes_v1_messages_proto_rawDescOnce sync.Once
	file_api_notes_v1_messages_proto_rawDescData []byte
)

func file_api_notes_v1_messages_proto_rawDescGZIP() []byte {
	file_api_notes_v1_messages_proto_rawDescOnce.Do(func() {
		file_api_notes_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_notes_v1_messages_proto_rawDesc), len(file_api_notes_v1_messages_proto_rawDesc)))
	})
	return file_api_notes_v1_messages_proto_rawDescData
}

var file_api_notes_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_notes_v1_messages_proto_goTypes = []any{
	(*NoteIDRequest)(nil),         // 0: api.notes.v1.NoteIDRequest
	(*NoteCreateRequest)(nil),     // 1: api.notes.v1.NoteCreateRequest
	(*Note)(nil),                  // 2: api.notes.v1.Note
	(*NoteList)(nil),              // 3: api.notes.v1.NoteList
	(*NoteEvent)(nil),             // 4: api.notes.v1.NoteEvent
	(*EventResponse)(nil),         // 5: api.notes.v1.EventResponse
	(*Health)(nil),                // 6: api.notes.v1.Health
	(*Empty)(nil),                 // 7: api.notes.v1.Empty
	(*MetricRequest)(nil),         // 8: api.notes.v1.MetricRequest
	(*SummaryResponse)(nil),       // 9: api.notes.v1.SummaryResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_api_notes_v1_messages_proto_depIdxs = []int32{
	10, // 0: api.notes.v1.Note.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: api.notes.v1.Note.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: api.notes.v1.NoteList.notes:type_name -> api.notes.v1.Note
	4,  // 3: api.notes.v1.EventResponse.note:type_name -> api.notes.v1.NoteEvent
	6,  // 4: api.notes.v1.EventResponse.health:type_name -> api.notes.v1.Health
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_notes_v1_messages_proto_init() }
func file_api_notes_v1_messages_proto_init() {
	if File_api_notes_v1_messages_proto != nil {
		return
	}
	file_api_notes_v1_messages_proto_msgTypes[5].OneofWrappers = []any{
		(*EventResponse_Note)(nil),
		(*EventResponse_Health)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notes_v1_messages_proto_rawDesc), len(file_api_notes_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_notes_v1_messages_proto_goTypes,
		DependencyIndexes: file_api_notes_v1_messages_proto_depIdxs,
		MessageInfos:      file_api_notes_v1_messages_proto_msgTypes,
	}.Build()
	File_api_notes_v1_messages_proto = out.File
	file_api_notes_v1_messages_proto_goTypes = nil
	file_api_notes_v1_messages_proto_depIdxs = nil
}
