// Code generated by protoc-gen-fast-equal. DO NOT EDIT.
// source: api/notes/v1/messages.proto

package v1

// IsEqual is a method for fast comparison
func (m *NoteIDRequest) IsEqual(msg *NoteIDRequest) bool {
	if m.Id != msg.Id {
		return false
	}
	return true
}

// IsEqual is a method for fast comparison
func (m *NoteCreateRequest) IsEqual(msg *NoteCreateRequest) bool {
	if m.Title != msg.Title {
		return false
	}
	if m.Desc != msg.Desc {
		return false
	}
	return true
}

// IsEqual is a method for fast comparison
func (m *Note) IsEqual(msg *Note) bool {
	if m.Id != msg.Id {
		return false
	}
	if m.Title != msg.Title {
		return false
	}
	if m.Desc != msg.Desc {
		return false
	}
	if m.IsDel != msg.IsDel {
		return false
	}
	if m.CreatedAt != msg.CreatedAt {
		return false
	}
	if m.UpdatedAt != msg.UpdatedAt {
		return false
	}
	return true
}

// IsEqual is a method for fast comparison
func (m *NoteList) IsEqual(msg *NoteList) bool {
	if len(m.Notes) != len(msg.Notes) {
		return false
	}
	for i := 0; i < len(m.Notes); i++ {
		if !m.Notes[i].IsEqual(msg.Notes[i]) {
			return false
		}
	}
	return true
}

// IsEqual is a method for fast comparison
func (m *NoteEvent) IsEqual(msg *NoteEvent) bool {
	if m.Id != msg.Id {
		return false
	}
	if m.Title != msg.Title {
		return false
	}
	return true
}

// IsEqual is a method for fast comparison
func (m *Health) IsEqual(msg *Health) bool {
	if m.Message != msg.Message {
		return false
	}
	return true
}

// IsEqual is a method for fast comparison
func (m *MetricRequest) IsEqual(msg *MetricRequest) bool {
	if m.Number != msg.Number {
		return false
	}
	return true
}

// IsEqual is a method for fast comparison
func (m *SummaryResponse) IsEqual(msg *SummaryResponse) bool {
	if m.Summary != msg.Summary {
		return false
	}
	return true
}
