// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/notes/v1/notes.proto

package v1

import (
	datetime "google.golang.org/genproto/googleapis/type/datetime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NoteIDRequest - сообщение ID заметки
type NoteIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteIDRequest) Reset() {
	*x = NoteIDRequest{}
	mi := &file_api_notes_v1_notes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteIDRequest) ProtoMessage() {}

func (x *NoteIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_notes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteIDRequest.ProtoReflect.Descriptor instead.
func (*NoteIDRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_notes_proto_rawDescGZIP(), []int{0}
}

func (x *NoteIDRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// NoteCreateRequest - сообщение заметки для создания
type NoteCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteCreateRequest) Reset() {
	*x = NoteCreateRequest{}
	mi := &file_api_notes_v1_notes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteCreateRequest) ProtoMessage() {}

func (x *NoteCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_notes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteCreateRequest.ProtoReflect.Descriptor instead.
func (*NoteCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_notes_proto_rawDescGZIP(), []int{1}
}

func (x *NoteCreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteCreateRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

// Note - сообщение заметки
type Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	IsDel         bool                   `protobuf:"varint,4,opt,name=is_del,json=isDel,proto3" json:"is_del,omitempty"`
	CreatedAt     *datetime.DateTime     `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *datetime.DateTime     `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_api_notes_v1_notes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_notes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_notes_proto_rawDescGZIP(), []int{2}
}

func (x *Note) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Note) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Note) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Note) GetIsDel() bool {
	if x != nil {
		return x.IsDel
	}
	return false
}

func (x *Note) GetCreatedAt() *datetime.DateTime {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Note) GetUpdatedAt() *datetime.DateTime {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// NoteList - сообщение списка заметок
type NoteList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notes         []*Note                `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteList) Reset() {
	*x = NoteList{}
	mi := &file_api_notes_v1_notes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteList) ProtoMessage() {}

func (x *NoteList) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_notes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteList.ProtoReflect.Descriptor instead.
func (*NoteList) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_notes_proto_rawDescGZIP(), []int{3}
}

func (x *NoteList) GetNotes() []*Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

var File_api_notes_v1_notes_proto protoreflect.FileDescriptor

const file_api_notes_v1_notes_proto_rawDesc = "" +
	"\n" +
	"\x18api/notes/v1/notes.proto\x12\fapi.notes.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1agoogle/type/datetime.proto\"#\n" +
	"\rNoteIDRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"=\n" +
	"\x11NoteCreateRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\"\xc7\x01\n" +
	"\x04Note\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x15\n" +
	"\x06is_del\x18\x04 \x01(\bR\x05isDel\x124\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x15.google.type.DateTimeR\tcreatedAt\x124\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x15.google.type.DateTimeR\tupdatedAt\"4\n" +
	"\bNoteList\x12(\n" +
	"\x05notes\x18\x01 \x03(\v2\x12.api.notes.v1.NoteR\x05notes2\x93\x02\n" +
	"\aNoteAPI\x12C\n" +
	"\n" +
	"CreateNote\x12\x1f.api.notes.v1.NoteCreateRequest\x1a\x12.api.notes.v1.Note\"\x00\x12@\n" +
	"\vGetNoteByID\x12\x1b.api.notes.v1.NoteIDRequest\x1a\x12.api.notes.v1.Note\"\x00\x12<\n" +
	"\bGetNotes\x12\x16.google.protobuf.Empty\x1a\x16.api.notes.v1.NoteList\"\x00\x12C\n" +
	"\x0eDeleteNoteByID\x12\x1b.api.notes.v1.NoteIDRequest\x1a\x12.api.notes.v1.Note\"\x00B.Z,github.com/shft1/grpc-notes/pkg/api/notes/v1b\x06proto3"

var (
	file_api_notes_v1_notes_proto_rawDescOnce sync.Once
	file_api_notes_v1_notes_proto_rawDescData []byte
)

func file_api_notes_v1_notes_proto_rawDescGZIP() []byte {
	file_api_notes_v1_notes_proto_rawDescOnce.Do(func() {
		file_api_notes_v1_notes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_notes_v1_notes_proto_rawDesc), len(file_api_notes_v1_notes_proto_rawDesc)))
	})
	return file_api_notes_v1_notes_proto_rawDescData
}

var file_api_notes_v1_notes_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_notes_v1_notes_proto_goTypes = []any{
	(*NoteIDRequest)(nil),     // 0: api.notes.v1.NoteIDRequest
	(*NoteCreateRequest)(nil), // 1: api.notes.v1.NoteCreateRequest
	(*Note)(nil),              // 2: api.notes.v1.Note
	(*NoteList)(nil),          // 3: api.notes.v1.NoteList
	(*datetime.DateTime)(nil), // 4: google.type.DateTime
	(*emptypb.Empty)(nil),     // 5: google.protobuf.Empty
}
var file_api_notes_v1_notes_proto_depIdxs = []int32{
	4, // 0: api.notes.v1.Note.created_at:type_name -> google.type.DateTime
	4, // 1: api.notes.v1.Note.updated_at:type_name -> google.type.DateTime
	2, // 2: api.notes.v1.NoteList.notes:type_name -> api.notes.v1.Note
	1, // 3: api.notes.v1.NoteAPI.CreateNote:input_type -> api.notes.v1.NoteCreateRequest
	0, // 4: api.notes.v1.NoteAPI.GetNoteByID:input_type -> api.notes.v1.NoteIDRequest
	5, // 5: api.notes.v1.NoteAPI.GetNotes:input_type -> google.protobuf.Empty
	0, // 6: api.notes.v1.NoteAPI.DeleteNoteByID:input_type -> api.notes.v1.NoteIDRequest
	2, // 7: api.notes.v1.NoteAPI.CreateNote:output_type -> api.notes.v1.Note
	2, // 8: api.notes.v1.NoteAPI.GetNoteByID:output_type -> api.notes.v1.Note
	3, // 9: api.notes.v1.NoteAPI.GetNotes:output_type -> api.notes.v1.NoteList
	2, // 10: api.notes.v1.NoteAPI.DeleteNoteByID:output_type -> api.notes.v1.Note
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_notes_v1_notes_proto_init() }
func file_api_notes_v1_notes_proto_init() {
	if File_api_notes_v1_notes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notes_v1_notes_proto_rawDesc), len(file_api_notes_v1_notes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_notes_v1_notes_proto_goTypes,
		DependencyIndexes: file_api_notes_v1_notes_proto_depIdxs,
		MessageInfos:      file_api_notes_v1_notes_proto_msgTypes,
	}.Build()
	File_api_notes_v1_notes_proto = out.File
	file_api_notes_v1_notes_proto_goTypes = nil
	file_api_notes_v1_notes_proto_depIdxs = nil
}
