// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/notes/v1/notes.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NoteAPI_Create_FullMethodName     = "/api.notes.v1.NoteAPI/Create"
	NoteAPI_GetByID_FullMethodName    = "/api.notes.v1.NoteAPI/GetByID"
	NoteAPI_GetMulti_FullMethodName   = "/api.notes.v1.NoteAPI/GetMulti"
	NoteAPI_DeleteByID_FullMethodName = "/api.notes.v1.NoteAPI/DeleteByID"
)

// NoteAPIClient is the client API for NoteAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NoteAPI - сервис заметок
type NoteAPIClient interface {
	// Create - создание заметки
	Create(ctx context.Context, in *NoteCreateRequest, opts ...grpc.CallOption) (*Note, error)
	// GetByID - получение заметки по ID
	GetByID(ctx context.Context, in *NoteIDRequest, opts ...grpc.CallOption) (*Note, error)
	// GetMulti - получение всех заметок
	GetMulti(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NoteList, error)
	// DeleteByID - удалить заметку
	DeleteByID(ctx context.Context, in *NoteIDRequest, opts ...grpc.CallOption) (*Note, error)
}

type noteAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewNoteAPIClient(cc grpc.ClientConnInterface) NoteAPIClient {
	return &noteAPIClient{cc}
}

func (c *noteAPIClient) Create(ctx context.Context, in *NoteCreateRequest, opts ...grpc.CallOption) (*Note, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Note)
	err := c.cc.Invoke(ctx, NoteAPI_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteAPIClient) GetByID(ctx context.Context, in *NoteIDRequest, opts ...grpc.CallOption) (*Note, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Note)
	err := c.cc.Invoke(ctx, NoteAPI_GetByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteAPIClient) GetMulti(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NoteList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteList)
	err := c.cc.Invoke(ctx, NoteAPI_GetMulti_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteAPIClient) DeleteByID(ctx context.Context, in *NoteIDRequest, opts ...grpc.CallOption) (*Note, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Note)
	err := c.cc.Invoke(ctx, NoteAPI_DeleteByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoteAPIServer is the server API for NoteAPI service.
// All implementations must embed UnimplementedNoteAPIServer
// for forward compatibility.
//
// NoteAPI - сервис заметок
type NoteAPIServer interface {
	// Create - создание заметки
	Create(context.Context, *NoteCreateRequest) (*Note, error)
	// GetByID - получение заметки по ID
	GetByID(context.Context, *NoteIDRequest) (*Note, error)
	// GetMulti - получение всех заметок
	GetMulti(context.Context, *emptypb.Empty) (*NoteList, error)
	// DeleteByID - удалить заметку
	DeleteByID(context.Context, *NoteIDRequest) (*Note, error)
	mustEmbedUnimplementedNoteAPIServer()
}

// UnimplementedNoteAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNoteAPIServer struct{}

func (UnimplementedNoteAPIServer) Create(context.Context, *NoteCreateRequest) (*Note, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedNoteAPIServer) GetByID(context.Context, *NoteIDRequest) (*Note, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedNoteAPIServer) GetMulti(context.Context, *emptypb.Empty) (*NoteList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMulti not implemented")
}
func (UnimplementedNoteAPIServer) DeleteByID(context.Context, *NoteIDRequest) (*Note, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteByID not implemented")
}
func (UnimplementedNoteAPIServer) mustEmbedUnimplementedNoteAPIServer() {}
func (UnimplementedNoteAPIServer) testEmbeddedByValue()                 {}

// UnsafeNoteAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoteAPIServer will
// result in compilation errors.
type UnsafeNoteAPIServer interface {
	mustEmbedUnimplementedNoteAPIServer()
}

func RegisterNoteAPIServer(s grpc.ServiceRegistrar, srv NoteAPIServer) {
	// If the following call panics, it indicates UnimplementedNoteAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NoteAPI_ServiceDesc, srv)
}

func _NoteAPI_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).Create(ctx, req.(*NoteCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteAPI_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).GetByID(ctx, req.(*NoteIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteAPI_GetMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).GetMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_GetMulti_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).GetMulti(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteAPI_DeleteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).DeleteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_DeleteByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).DeleteByID(ctx, req.(*NoteIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NoteAPI_ServiceDesc is the grpc.ServiceDesc for NoteAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoteAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.notes.v1.NoteAPI",
	HandlerType: (*NoteAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _NoteAPI_Create_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _NoteAPI_GetByID_Handler,
		},
		{
			MethodName: "GetMulti",
			Handler:    _NoteAPI_GetMulti_Handler,
		},
		{
			MethodName: "DeleteByID",
			Handler:    _NoteAPI_DeleteByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/notes/v1/notes.proto",
}
