// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/notes/v1/notes.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_notes_v1_notes_proto protoreflect.FileDescriptor

const file_api_notes_v1_notes_proto_rawDesc = "" +
	"\n" +
	"\x18api/notes/v1/notes.proto\x12\fapi.notes.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bapi/notes/v1/messages.proto2\x9d\x05\n" +
	"\aNoteAPI\x12W\n" +
	"\x06Create\x12\x1f.api.notes.v1.NoteCreateRequest\x1a\x12.api.notes.v1.Note\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/notes/gen/v1\x12V\n" +
	"\aGetByID\x12\x1b.api.notes.v1.NoteIDRequest\x1a\x12.api.notes.v1.Note\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/notes/gen/v1/{id}\x12Q\n" +
	"\bGetMulti\x12\x16.google.protobuf.Empty\x1a\x16.api.notes.v1.NoteList\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/notes/gen/v1\x12Y\n" +
	"\n" +
	"DeleteByID\x12\x1b.api.notes.v1.NoteIDRequest\x1a\x12.api.notes.v1.Note\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/notes/gen/v1/{id}\x12h\n" +
	"\x11SubscribeToEvents\x12\x13.api.notes.v1.Empty\x1a\x1b.api.notes.v1.EventResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/notes/gen/v1/subscribe0\x01\x12s\n" +
	"\rUploadMetrics\x12\x1b.api.notes.v1.MetricRequest\x1a\x1d.api.notes.v1.SummaryResponse\"$\x82\xd3\xe4\x93\x02\x1e\"\x1c/notes/gen/v1/metrics/upload(\x01\x12T\n" +
	"\x04Chat\x12\x15.api.notes.v1.Message\x1a\x15.api.notes.v1.Message\"\x1a\x82\xd3\xe4\x93\x02\x14\"\x12/notes/gen/v1/chat(\x010\x01B.Z,github.com/shft1/grpc-notes/pkg/api/notes/v1b\x06proto3"

var file_api_notes_v1_notes_proto_goTypes = []any{
	(*NoteCreateRequest)(nil), // 0: api.notes.v1.NoteCreateRequest
	(*NoteIDRequest)(nil),     // 1: api.notes.v1.NoteIDRequest
	(*emptypb.Empty)(nil),     // 2: google.protobuf.Empty
	(*Empty)(nil),             // 3: api.notes.v1.Empty
	(*MetricRequest)(nil),     // 4: api.notes.v1.MetricRequest
	(*Message)(nil),           // 5: api.notes.v1.Message
	(*Note)(nil),              // 6: api.notes.v1.Note
	(*NoteList)(nil),          // 7: api.notes.v1.NoteList
	(*EventResponse)(nil),     // 8: api.notes.v1.EventResponse
	(*SummaryResponse)(nil),   // 9: api.notes.v1.SummaryResponse
}
var file_api_notes_v1_notes_proto_depIdxs = []int32{
	0, // 0: api.notes.v1.NoteAPI.Create:input_type -> api.notes.v1.NoteCreateRequest
	1, // 1: api.notes.v1.NoteAPI.GetByID:input_type -> api.notes.v1.NoteIDRequest
	2, // 2: api.notes.v1.NoteAPI.GetMulti:input_type -> google.protobuf.Empty
	1, // 3: api.notes.v1.NoteAPI.DeleteByID:input_type -> api.notes.v1.NoteIDRequest
	3, // 4: api.notes.v1.NoteAPI.SubscribeToEvents:input_type -> api.notes.v1.Empty
	4, // 5: api.notes.v1.NoteAPI.UploadMetrics:input_type -> api.notes.v1.MetricRequest
	5, // 6: api.notes.v1.NoteAPI.Chat:input_type -> api.notes.v1.Message
	6, // 7: api.notes.v1.NoteAPI.Create:output_type -> api.notes.v1.Note
	6, // 8: api.notes.v1.NoteAPI.GetByID:output_type -> api.notes.v1.Note
	7, // 9: api.notes.v1.NoteAPI.GetMulti:output_type -> api.notes.v1.NoteList
	6, // 10: api.notes.v1.NoteAPI.DeleteByID:output_type -> api.notes.v1.Note
	8, // 11: api.notes.v1.NoteAPI.SubscribeToEvents:output_type -> api.notes.v1.EventResponse
	9, // 12: api.notes.v1.NoteAPI.UploadMetrics:output_type -> api.notes.v1.SummaryResponse
	5, // 13: api.notes.v1.NoteAPI.Chat:output_type -> api.notes.v1.Message
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_notes_v1_notes_proto_init() }
func file_api_notes_v1_notes_proto_init() {
	if File_api_notes_v1_notes_proto != nil {
		return
	}
	file_api_notes_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notes_v1_notes_proto_rawDesc), len(file_api_notes_v1_notes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_notes_v1_notes_proto_goTypes,
		DependencyIndexes: file_api_notes_v1_notes_proto_depIdxs,
	}.Build()
	File_api_notes_v1_notes_proto = out.File
	file_api_notes_v1_notes_proto_goTypes = nil
	file_api_notes_v1_notes_proto_depIdxs = nil
}
