// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/notes/v1/notes.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NoteAPI_CreateNote_FullMethodName     = "/api.notes.v1.NoteAPI/CreateNote"
	NoteAPI_GetNoteByID_FullMethodName    = "/api.notes.v1.NoteAPI/GetNoteByID"
	NoteAPI_GetNotes_FullMethodName       = "/api.notes.v1.NoteAPI/GetNotes"
	NoteAPI_DeleteNoteByID_FullMethodName = "/api.notes.v1.NoteAPI/DeleteNoteByID"
)

// NoteAPIClient is the client API for NoteAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NoteAPI - сервис заметок
type NoteAPIClient interface {
	// CreateNote - создание заметки
	CreateNote(ctx context.Context, in *NoteCreateRequest, opts ...grpc.CallOption) (*Note, error)
	// GetNoteByID - получение заметки по ID
	GetNoteByID(ctx context.Context, in *NoteIDRequest, opts ...grpc.CallOption) (*Note, error)
	// GetNotes - получение всех заметок
	GetNotes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NoteList, error)
	// DeleteNoteByID - удалить заметку
	DeleteNoteByID(ctx context.Context, in *NoteIDRequest, opts ...grpc.CallOption) (*Note, error)
}

type noteAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewNoteAPIClient(cc grpc.ClientConnInterface) NoteAPIClient {
	return &noteAPIClient{cc}
}

func (c *noteAPIClient) CreateNote(ctx context.Context, in *NoteCreateRequest, opts ...grpc.CallOption) (*Note, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Note)
	err := c.cc.Invoke(ctx, NoteAPI_CreateNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteAPIClient) GetNoteByID(ctx context.Context, in *NoteIDRequest, opts ...grpc.CallOption) (*Note, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Note)
	err := c.cc.Invoke(ctx, NoteAPI_GetNoteByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteAPIClient) GetNotes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NoteList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteList)
	err := c.cc.Invoke(ctx, NoteAPI_GetNotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteAPIClient) DeleteNoteByID(ctx context.Context, in *NoteIDRequest, opts ...grpc.CallOption) (*Note, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Note)
	err := c.cc.Invoke(ctx, NoteAPI_DeleteNoteByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoteAPIServer is the server API for NoteAPI service.
// All implementations must embed UnimplementedNoteAPIServer
// for forward compatibility.
//
// NoteAPI - сервис заметок
type NoteAPIServer interface {
	// CreateNote - создание заметки
	CreateNote(context.Context, *NoteCreateRequest) (*Note, error)
	// GetNoteByID - получение заметки по ID
	GetNoteByID(context.Context, *NoteIDRequest) (*Note, error)
	// GetNotes - получение всех заметок
	GetNotes(context.Context, *emptypb.Empty) (*NoteList, error)
	// DeleteNoteByID - удалить заметку
	DeleteNoteByID(context.Context, *NoteIDRequest) (*Note, error)
	mustEmbedUnimplementedNoteAPIServer()
}

// UnimplementedNoteAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNoteAPIServer struct{}

func (UnimplementedNoteAPIServer) CreateNote(context.Context, *NoteCreateRequest) (*Note, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNote not implemented")
}
func (UnimplementedNoteAPIServer) GetNoteByID(context.Context, *NoteIDRequest) (*Note, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNoteByID not implemented")
}
func (UnimplementedNoteAPIServer) GetNotes(context.Context, *emptypb.Empty) (*NoteList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNotes not implemented")
}
func (UnimplementedNoteAPIServer) DeleteNoteByID(context.Context, *NoteIDRequest) (*Note, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNoteByID not implemented")
}
func (UnimplementedNoteAPIServer) mustEmbedUnimplementedNoteAPIServer() {}
func (UnimplementedNoteAPIServer) testEmbeddedByValue()                 {}

// UnsafeNoteAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoteAPIServer will
// result in compilation errors.
type UnsafeNoteAPIServer interface {
	mustEmbedUnimplementedNoteAPIServer()
}

func RegisterNoteAPIServer(s grpc.ServiceRegistrar, srv NoteAPIServer) {
	// If the following call panics, it indicates UnimplementedNoteAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NoteAPI_ServiceDesc, srv)
}

func _NoteAPI_CreateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).CreateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_CreateNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).CreateNote(ctx, req.(*NoteCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteAPI_GetNoteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).GetNoteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_GetNoteByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).GetNoteByID(ctx, req.(*NoteIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteAPI_GetNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).GetNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_GetNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).GetNotes(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteAPI_DeleteNoteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).DeleteNoteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_DeleteNoteByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).DeleteNoteByID(ctx, req.(*NoteIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NoteAPI_ServiceDesc is the grpc.ServiceDesc for NoteAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoteAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.notes.v1.NoteAPI",
	HandlerType: (*NoteAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNote",
			Handler:    _NoteAPI_CreateNote_Handler,
		},
		{
			MethodName: "GetNoteByID",
			Handler:    _NoteAPI_GetNoteByID_Handler,
		},
		{
			MethodName: "GetNotes",
			Handler:    _NoteAPI_GetNotes_Handler,
		},
		{
			MethodName: "DeleteNoteByID",
			Handler:    _NoteAPI_DeleteNoteByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/notes/v1/notes.proto",
}
