// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/notes/v1/notes.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NoteAPI_Create_FullMethodName            = "/api.notes.v1.NoteAPI/Create"
	NoteAPI_GetByID_FullMethodName           = "/api.notes.v1.NoteAPI/GetByID"
	NoteAPI_GetMulti_FullMethodName          = "/api.notes.v1.NoteAPI/GetMulti"
	NoteAPI_DeleteByID_FullMethodName        = "/api.notes.v1.NoteAPI/DeleteByID"
	NoteAPI_SubscribeToEvents_FullMethodName = "/api.notes.v1.NoteAPI/SubscribeToEvents"
	NoteAPI_UploadMetrics_FullMethodName     = "/api.notes.v1.NoteAPI/UploadMetrics"
	NoteAPI_Chat_FullMethodName              = "/api.notes.v1.NoteAPI/Chat"
)

// NoteAPIClient is the client API for NoteAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NoteAPI - сервис заметок
type NoteAPIClient interface {
	// Create - создание заметки
	Create(ctx context.Context, in *NoteCreateRequest, opts ...grpc.CallOption) (*Note, error)
	// GetByID - получение заметки по ID
	GetByID(ctx context.Context, in *NoteIDRequest, opts ...grpc.CallOption) (*Note, error)
	// GetMulti - получение всех заметок
	GetMulti(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NoteList, error)
	// DeleteByID - удалить заметку
	DeleteByID(ctx context.Context, in *NoteIDRequest, opts ...grpc.CallOption) (*Note, error)
	// SubscribeToEvents - подписка на событие "создание заметки"
	SubscribeToEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventResponse], error)
	// UploadMetrics - загрузка метрик
	UploadMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricRequest, SummaryResponse], error)
	// Chat - двусторонний чат
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error)
}

type noteAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewNoteAPIClient(cc grpc.ClientConnInterface) NoteAPIClient {
	return &noteAPIClient{cc}
}

func (c *noteAPIClient) Create(ctx context.Context, in *NoteCreateRequest, opts ...grpc.CallOption) (*Note, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Note)
	err := c.cc.Invoke(ctx, NoteAPI_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteAPIClient) GetByID(ctx context.Context, in *NoteIDRequest, opts ...grpc.CallOption) (*Note, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Note)
	err := c.cc.Invoke(ctx, NoteAPI_GetByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteAPIClient) GetMulti(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NoteList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteList)
	err := c.cc.Invoke(ctx, NoteAPI_GetMulti_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteAPIClient) DeleteByID(ctx context.Context, in *NoteIDRequest, opts ...grpc.CallOption) (*Note, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Note)
	err := c.cc.Invoke(ctx, NoteAPI_DeleteByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteAPIClient) SubscribeToEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NoteAPI_ServiceDesc.Streams[0], NoteAPI_SubscribeToEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, EventResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NoteAPI_SubscribeToEventsClient = grpc.ServerStreamingClient[EventResponse]

func (c *noteAPIClient) UploadMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricRequest, SummaryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NoteAPI_ServiceDesc.Streams[1], NoteAPI_UploadMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricRequest, SummaryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NoteAPI_UploadMetricsClient = grpc.ClientStreamingClient[MetricRequest, SummaryResponse]

func (c *noteAPIClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NoteAPI_ServiceDesc.Streams[2], NoteAPI_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, Message]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NoteAPI_ChatClient = grpc.BidiStreamingClient[Message, Message]

// NoteAPIServer is the server API for NoteAPI service.
// All implementations must embed UnimplementedNoteAPIServer
// for forward compatibility.
//
// NoteAPI - сервис заметок
type NoteAPIServer interface {
	// Create - создание заметки
	Create(context.Context, *NoteCreateRequest) (*Note, error)
	// GetByID - получение заметки по ID
	GetByID(context.Context, *NoteIDRequest) (*Note, error)
	// GetMulti - получение всех заметок
	GetMulti(context.Context, *emptypb.Empty) (*NoteList, error)
	// DeleteByID - удалить заметку
	DeleteByID(context.Context, *NoteIDRequest) (*Note, error)
	// SubscribeToEvents - подписка на событие "создание заметки"
	SubscribeToEvents(*Empty, grpc.ServerStreamingServer[EventResponse]) error
	// UploadMetrics - загрузка метрик
	UploadMetrics(grpc.ClientStreamingServer[MetricRequest, SummaryResponse]) error
	// Chat - двусторонний чат
	Chat(grpc.BidiStreamingServer[Message, Message]) error
	mustEmbedUnimplementedNoteAPIServer()
}

// UnimplementedNoteAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNoteAPIServer struct{}

func (UnimplementedNoteAPIServer) Create(context.Context, *NoteCreateRequest) (*Note, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedNoteAPIServer) GetByID(context.Context, *NoteIDRequest) (*Note, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedNoteAPIServer) GetMulti(context.Context, *emptypb.Empty) (*NoteList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMulti not implemented")
}
func (UnimplementedNoteAPIServer) DeleteByID(context.Context, *NoteIDRequest) (*Note, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteByID not implemented")
}
func (UnimplementedNoteAPIServer) SubscribeToEvents(*Empty, grpc.ServerStreamingServer[EventResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeToEvents not implemented")
}
func (UnimplementedNoteAPIServer) UploadMetrics(grpc.ClientStreamingServer[MetricRequest, SummaryResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadMetrics not implemented")
}
func (UnimplementedNoteAPIServer) Chat(grpc.BidiStreamingServer[Message, Message]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedNoteAPIServer) mustEmbedUnimplementedNoteAPIServer() {}
func (UnimplementedNoteAPIServer) testEmbeddedByValue()                 {}

// UnsafeNoteAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoteAPIServer will
// result in compilation errors.
type UnsafeNoteAPIServer interface {
	mustEmbedUnimplementedNoteAPIServer()
}

func RegisterNoteAPIServer(s grpc.ServiceRegistrar, srv NoteAPIServer) {
	// If the following call panics, it indicates UnimplementedNoteAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NoteAPI_ServiceDesc, srv)
}

func _NoteAPI_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).Create(ctx, req.(*NoteCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteAPI_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).GetByID(ctx, req.(*NoteIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteAPI_GetMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).GetMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_GetMulti_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).GetMulti(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteAPI_DeleteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).DeleteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_DeleteByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).DeleteByID(ctx, req.(*NoteIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteAPI_SubscribeToEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NoteAPIServer).SubscribeToEvents(m, &grpc.GenericServerStream[Empty, EventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NoteAPI_SubscribeToEventsServer = grpc.ServerStreamingServer[EventResponse]

func _NoteAPI_UploadMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NoteAPIServer).UploadMetrics(&grpc.GenericServerStream[MetricRequest, SummaryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NoteAPI_UploadMetricsServer = grpc.ClientStreamingServer[MetricRequest, SummaryResponse]

func _NoteAPI_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NoteAPIServer).Chat(&grpc.GenericServerStream[Message, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NoteAPI_ChatServer = grpc.BidiStreamingServer[Message, Message]

// NoteAPI_ServiceDesc is the grpc.ServiceDesc for NoteAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoteAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.notes.v1.NoteAPI",
	HandlerType: (*NoteAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _NoteAPI_Create_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _NoteAPI_GetByID_Handler,
		},
		{
			MethodName: "GetMulti",
			Handler:    _NoteAPI_GetMulti_Handler,
		},
		{
			MethodName: "DeleteByID",
			Handler:    _NoteAPI_DeleteByID_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToEvents",
			Handler:       _NoteAPI_SubscribeToEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadMetrics",
			Handler:       _NoteAPI_UploadMetrics_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Chat",
			Handler:       _NoteAPI_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/notes/v1/notes.proto",
}
